version: '1.2'
service:
  name: user-management-service
  description: >-
    This service handles user registration, authentication, and profile
    management.
  environment: production
environments:
  production:
    database:
      password: supersecretpassword
      host: prod-db.company.com
      port: 5432
      username: prod_user
    redis:
      port: 1234
      host: prod-redis.company.com
    replicas: 5
    logging:
      level: INFO
      format: json
secrets: defaultpassword123
users:
  admin:
    username: admin_user
    password: defaultpassword123
  guest:
    username: guest_user
    password: defaultpassword123
endpoints:
  - path: /users
    method: GET
    description: Fetch list of users
    authentication: true
    cache: true
  - path: /users/{id}
    method: GET
    description: Fetch user by ID
    authentication: true
    cache: true
  - path: /users
    method: POST
    description: Register a new user
    authentication: false
    cache: false
healthCheck:
  endpoint: /health
  interval: 30
  timeout: 5
retryPolicy:
  retries: 3
  backoff: 200
cronJobs:
  cleanup:
    schedule: 0 0 * * *
    command: cleanup-users
    timeout: 60
features:
  userDeletionEnabled: true
  twoFactorAuthentication: false
